# Generated by Django 3.2.16 on 2024-05-17 20:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Collect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gathering_name', models.CharField(max_length=100, verbose_name='Название сбора')),
                ('donation_purpose', models.CharField(choices=[('Birthday', 'День рождения'), ('Wedding', 'Свадьба'), ('Charity', 'Благотворительность')], max_length=200, verbose_name='Цель сбора')),
                ('description', models.TextField(verbose_name='Описание сбора')),
                ('all_amount', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Запланированная сумма')),
                ('current_amount', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=8, null=True, verbose_name='Собрано')),
                ('donators_count', models.PositiveIntegerField(default=0, verbose_name='Количество пожертвовавших')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='Обложка сбора')),
                ('end_datetime', models.DateTimeField(verbose_name='Дата и время завершения сбора')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collects', to=settings.AUTH_USER_MODEL, verbose_name='Автор сбора')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Сумма платежа')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата платежа')),
                ('collect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='gathering.collect', verbose_name='Сбор')),
                ('donator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL, verbose_name='Пожертвователь')),
            ],
        ),
    ]
